package br.com.barbara.Classes;
// Generated 14/12/2018 16:05:11 by Hibernate Tools 4.3.1



/**
 * Controleparcela generated by hbm2java
 */
public class Controleparcela  implements java.io.Serializable {


     private Integer idcontrole;
     private int idcliente;
     private float vltotal;
     private Integer controle;
     private Integer quantParcela;
     private float vlentrada;

    public float getVlentrada() {
        return vlentrada;
    }

    public void setVlentrada(float vlentrada) {
        this.vlentrada = vlentrada;
    }
    public Integer getQuantParcela() {
        return quantParcela;
    }

    public void setQuantParcela(Integer quantParcela) {
        this.quantParcela = quantParcela;
    }
    public Controleparcela() {
    }

	
    public Controleparcela(int idcliente, float vltotal, int Integer, float vlentrada) {
        this.idcliente = idcliente;
        this.vltotal = vltotal;
        this.quantParcela = quantParcela;
        this.vlentrada = vlentrada;
    }
    public Controleparcela(int idcliente, float vltotal, Integer controle, int Integer, float vlentrada) {
       this.idcliente = idcliente;
       this.vltotal = vltotal;
       this.controle = controle;
       this.quantParcela = quantParcela;
       this.vlentrada = vlentrada;
    }
   
    public Integer getIdcontrole() {
        return this.idcontrole;
    }
    
    public void setIdcontrole(Integer idcontrole) {
        this.idcontrole = idcontrole;
    }
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public float getVltotal() {
        return this.vltotal;
    }
    
    public void setVltotal(float vltotal) {
        this.vltotal = vltotal;
    }
    public Integer getControle() {
        return this.controle;
    }
    
    public void setControle(Integer controle) {
        this.controle = controle;
    }




}


