package br.com.barbara.Classes;
// Generated 14/12/2018 16:05:11 by Hibernate Tools 4.3.1



/**
 * Estoque generated by hbm2java
 */
public class Estoque  implements java.io.Serializable {


     private Integer idEstoque;
     private int idProduto;
     private float quantidade;
     private float quantCaixa;
     private Float quantVenda;
     private float custo;
     private float porcentagem;
     private float venda;

    public Estoque() {
    }

	
    public Estoque(int idProduto, float quantidade, float quantCaixa, float custo, float porcentagem, float venda) {
        this.idProduto = idProduto;
        this.quantidade = quantidade;
        this.quantCaixa = quantCaixa;
        this.custo = custo;
        this.porcentagem = porcentagem;
        this.venda = venda;
    }
    public Estoque(int idProduto, float quantidade, float quantCaixa, Float quantVenda, float custo, float porcentagem, float venda) {
       this.idProduto = idProduto;
       this.quantidade = quantidade;
       this.quantCaixa = quantCaixa;
       this.quantVenda = quantVenda;
       this.custo = custo;
       this.porcentagem = porcentagem;
       this.venda = venda;
    }
   
    public Integer getIdEstoque() {
        return this.idEstoque;
    }
    
    public void setIdEstoque(Integer idEstoque) {
        this.idEstoque = idEstoque;
    }
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public float getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(float quantidade) {
        this.quantidade = quantidade;
    }
    public float getQuantCaixa() {
        return this.quantCaixa;
    }
    
    public void setQuantCaixa(float quantCaixa) {
        this.quantCaixa = quantCaixa;
    }
    public Float getQuantVenda() {
        return this.quantVenda;
    }
    
    public void setQuantVenda(Float quantVenda) {
        this.quantVenda = quantVenda;
    }
    public float getCusto() {
        return this.custo;
    }
    
    public void setCusto(float custo) {
        this.custo = custo;
    }
    public float getPorcentagem() {
        return this.porcentagem;
    }
    
    public void setPorcentagem(float porcentagem) {
        this.porcentagem = porcentagem;
    }
    public float getVenda() {
        return this.venda;
    }
    
    public void setVenda(float venda) {
        this.venda = venda;
    }




}


