package br.com.barbara.Classes;
// Generated 14/12/2018 16:05:11 by Hibernate Tools 4.3.1



/**
 * Fornecedores generated by hbm2java
 */
public class Fornecedores  implements java.io.Serializable {


     private Integer idForn;
     private String nomeForn;
     private String cnpjCpf;
     private String telefone;
     private String email;
     private String endereco;

    public Fornecedores() {
    }

	
    public Fornecedores(String nomeForn, String cnpjCpf) {
        this.nomeForn = nomeForn;
        this.cnpjCpf = cnpjCpf;
    }
    public Fornecedores(String nomeForn, String cnpjCpf, String telefone, String email, String endereco) {
       this.nomeForn = nomeForn;
       this.cnpjCpf = cnpjCpf;
       this.telefone = telefone;
       this.email = email;
       this.endereco = endereco;
    }
   
    public Integer getIdForn() {
        return this.idForn;
    }
    
    public void setIdForn(Integer idForn) {
        this.idForn = idForn;
    }
    public String getNomeForn() {
        return this.nomeForn;
    }
    
    public void setNomeForn(String nomeForn) {
        this.nomeForn = nomeForn;
    }
    public String getCnpjCpf() {
        return this.cnpjCpf;
    }
    
    public void setCnpjCpf(String cnpjCpf) {
        this.cnpjCpf = cnpjCpf;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }




}


