package br.com.barbara.Classes;
// Generated 14/12/2018 16:05:11 by Hibernate Tools 4.3.1



/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer idMarca;
     private String nomeMarca;
     private int idFornecedor;
     private String modelo;

    public Marca() {
    }

	
    public Marca(String nomeMarca, int idFornecedor) {
        this.nomeMarca = nomeMarca;
        this.idFornecedor = idFornecedor;
    }
    public Marca(String nomeMarca, int idFornecedor, String modelo) {
       this.nomeMarca = nomeMarca;
       this.idFornecedor = idFornecedor;
       this.modelo = modelo;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public String getNomeMarca() {
        return this.nomeMarca;
    }
    
    public void setNomeMarca(String nomeMarca) {
        this.nomeMarca = nomeMarca;
    }
    public int getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }




}


