package br.com.barbara.Classes;
// Generated 14/12/2018 16:05:11 by Hibernate Tools 4.3.1



/**
 * Parcela generated by hbm2java
 */
public class Parcela  implements java.io.Serializable {


     private Integer idparcela;
     private int idcliente;
     private int numparcela;
     private float valorparcela;
     private Integer pago;
     private int numvenda;

    public int getNumvenda() {
        return numvenda;
    }

    public void setNumvenda(int numvenda) {
        this.numvenda = numvenda;
    }
    public Parcela() {
    }

	
    public Parcela(int idcliente, int numparcela, float valorparcela, int numvenda) {
        this.idcliente = idcliente;
        this.numparcela = numparcela;
        this.valorparcela = valorparcela;
        this.numvenda = numparcela;
    }
    public Parcela(int idcliente, int numparcela, float valorparcela, Integer pago, int numvenda) {
       this.idcliente = idcliente;
       this.numparcela = numparcela;
       this.valorparcela = valorparcela;
       this.pago = pago;
       this.numvenda = numparcela;
    }
   
    public Integer getIdparcela() {
        return this.idparcela;
    }
    
    public void setIdparcela(Integer idparcela) {
        this.idparcela = idparcela;
    }
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public int getNumparcela() {
        return this.numparcela;
    }
    
    public void setNumparcela(int numparcela) {
        this.numparcela = numparcela;
    }
    public float getValorparcela() {
        return this.valorparcela;
    }
    
    public void setValorparcela(float valorparcela) {
        this.valorparcela = valorparcela;
    }
    public Integer getPago() {
        return this.pago;
    }
    
    public void setPago(Integer pago) {
        this.pago = pago;
    }




}


