package br.com.barbara.Classes;
// Generated 14/12/2018 16:05:11 by Hibernate Tools 4.3.1



/**
 * Produtos generated by hbm2java
 */
public class Produtos  implements java.io.Serializable {


     private Integer idProduto;
     private String descricao;
     private String unidadeCompra;
     private String unidadeVenda;
     private int idFornecedor;
     private int idMarca;

    public Produtos() {
    }

    public Produtos(String descricao, String unidadeCompra, String unidadeVenda, int idFornecedor, int idMarca) {
       this.descricao = descricao;
       this.unidadeCompra = unidadeCompra;
       this.unidadeVenda = unidadeVenda;
       this.idFornecedor = idFornecedor;
       this.idMarca = idMarca;
    }
   
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getUnidadeCompra() {
        return this.unidadeCompra;
    }
    
    public void setUnidadeCompra(String unidadeCompra) {
        this.unidadeCompra = unidadeCompra;
    }
    public String getUnidadeVenda() {
        return this.unidadeVenda;
    }
    
    public void setUnidadeVenda(String unidadeVenda) {
        this.unidadeVenda = unidadeVenda;
    }
    public int getIdFornecedor() {
        return this.idFornecedor;
    }
    
    public void setIdFornecedor(int idFornecedor) {
        this.idFornecedor = idFornecedor;
    }
    public int getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(int idMarca) {
        this.idMarca = idMarca;
    }




}


