package br.com.barbara.Classes;
// Generated 14/12/2018 16:05:11 by Hibernate Tools 4.3.1



/**
 * Recibovenda generated by hbm2java
 */
public class Recibovenda  implements java.io.Serializable {


     private Integer idvenda;
     private int idcliente;
     private String datavenda;

    public Recibovenda() {
    }

    public Recibovenda(int idcliente, String datavenda) {
       this.idcliente = idcliente;
       this.datavenda = datavenda;
    }
   
    public Integer getIdvenda() {
        return this.idvenda;
    }
    
    public void setIdvenda(Integer idvenda) {
        this.idvenda = idvenda;
    }
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getDatavenda() {
        return this.datavenda;
    }
    
    public void setDatavenda(String datavenda) {
        this.datavenda = datavenda;
    }




}


