/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.barbara.visao;

import Util.HibernateUtil;
import br.com.barbara.Classes.Fornecedores;
import br.com.barbara.Classes.Marca;
import br.com.barbara.Classes.Produtos;
import br.com.barbara.models.SalvaProduto;
import java.awt.List;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import org.hibernate.Criteria;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Antonio Rony
 */
public class GerenciamentoProd extends javax.swing.JDialog {
  private  DefaultTableModel tmResultSet = new DefaultTableModel(null, new String[]{"ID","DESCRIÇÃO","FORNECEDOR", "MARCA", "UNI COMPRA","UNI VENDA"});;
   java.util.List<Produtos> resultado;  
      private ListSelectionModel lsmResult;
      private DefaultTableModel tabela;

        int  id;
        String  descricao;
        String  unCompra;
        String  unVenda;
        int  fornecedor;
        int  marca;
          
  /**
     * Creates new form GerenciamentoProd
     */
    public GerenciamentoProd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupF = new javax.swing.JPopupMenu();
        jPMARCA = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTDesc = new javax.swing.JTextField();
        jCUn = new javax.swing.JComboBox<>();
        jVUn = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTPesq = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTForn = new javax.swing.JTextField();
        jTMarca = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIA DE PRODUTOS - SCE - TEC.INOVA");

        jPanel1.setBackground(new java.awt.Color(254, 131, 159));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DESCRIÇÃO ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UNIDADE COMPRA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("UNIDADE VENDA");

        jCUn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UN", "CX", "PC", "PCT" }));

        jVUn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UN", "CX", "PC", "PCT" }));

        jTable1.setModel(tmResultSet);
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         lsmResult = jTable1.getSelectionModel();
         lsmResult.addListSelectionListener(new ListSelectionListener() { 
             public void valueChanged(ListSelectionEvent e) {
                 
                     if (! e.getValueIsAdjusting()){ 
                         jTTabelaLinhaSelecionada(jTable1); 
                     }
                
                  }
         });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("ADICIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("PESQUISAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORNECEDOR");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MARCA");

        jTForn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFornKeyPressed(evt);
            }
        });

        jTMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTMarcaKeyPressed(evt);
            }
        });

        jButton4.setText("EXCLUIR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("ALTERAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTDesc)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jVUn, 0, 54, Short.MAX_VALUE)
                                    .addComponent(jCUn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTForn)
                                    .addComponent(jTMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 310, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jTForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jVUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        SalvaProduto salvaP = new SalvaProduto();
        
        Produtos produtos = new Produtos();
        produtos.setDescricao(jTDesc.getText());
        produtos.setIdFornecedor(1);
        produtos.setIdMarca(1);
        produtos.setUnidadeCompra(jCUn.getItemAt(1).toString());
        produtos.setUnidadeVenda(jVUn.getItemAt(1).toString());
        
        
        salvaP.salvaProduto(produtos);
        limparCampos();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(jTPesq.getText().equalsIgnoreCase("")){try{mostraPesquisa();}catch(Exception e){System.out.print(e);}}
else{pesquisaSelecionada(jTPesq.getText());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
limparCampos();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Produtos produtos = new Produtos();
    Session s = HibernateUtil.getSessionFactory().openSession();
        produtos.setIdProduto(this.id);
        produtos.setDescricao(jTDesc.getText());
        produtos.setIdFornecedor(2);
        produtos.setIdMarca(1);
        produtos.setUnidadeCompra(jCUn.getItemAt(1).toString());
        produtos.setUnidadeVenda(jVUn.getItemAt(1).toString());        
        s.beginTransaction();
        s.update(produtos);
        s.getTransaction().commit();
        
        JOptionPane.showMessageDialog(rootPane,"ALTERADO COM SUCESSO!");
        limparCampos();
        mostraPesquisa();
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

  Produtos produtos = new Produtos();
     Session s = HibernateUtil.getSessionFactory().openSession();
        produtos.setIdProduto(this.id);
        produtos.setDescricao(jTDesc.getText());
        produtos.setIdFornecedor(2);
        produtos.setIdMarca(1);
        produtos.setUnidadeCompra(jCUn.getItemAt(1).toString());
        produtos.setUnidadeVenda(jVUn.getItemAt(1).toString());        
        s.beginTransaction();
        s.delete(produtos);
        s.getTransaction().commit();
        
        JOptionPane.showMessageDialog(rootPane,"EXCLUIDO COM SUCESSO!");
        limparCampos();
        mostraPesquisa();
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTFornKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFornKeyPressed
  if (evt.getKeyCode() == evt.VK_SPACE) {
        jPopupF.removeAll();

        mostraPesquisaFiltro(jTForn.getText());

            jTForn.add(jPopupF);
            jTForn.setComponentPopupMenu(jPopupF);

            try {
                int dotPosition = jTForn.getCaretPosition();
                Rectangle popupLocation = jTForn.modelToView(dotPosition);
                jPopupF.show(jTForn, popupLocation.x, popupLocation.y+30);
                jTForn.setFocusable(true);
            } catch (BadLocationException badLocationException) {
                System.out.println("Oops");
            }
          }        // TODO add your handling code here:
    }//GEN-LAST:event_jTFornKeyPressed

    private void jTMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMarcaKeyPressed
  if (evt.getKeyCode() == evt.VK_SPACE) {
        jPMARCA.removeAll();

        mostraPesquisaFiltroMarca(jTMarca.getText());

            jTMarca.add(jPMARCA);
            jTMarca.setComponentPopupMenu(jPMARCA);

            try {
                int dotPosition = jTMarca.getCaretPosition();
                Rectangle popupLocation = jTMarca.modelToView(dotPosition);
                jPMARCA.show(jTMarca, popupLocation.x, popupLocation.y+30);
                jTMarca.setFocusable(true);
            } catch (BadLocationException badLocationException) {
                System.out.println("Oops");
            }
          }  

        // TODO add your handling code here:
    }//GEN-LAST:event_jTMarcaKeyPressed

    public void limparCampos(){
        jTDesc.setText("");
        jTForn.setText("");
        jTMarca.setText("");
        jCUn.setSelectedIndex(0);
        jVUn.setSelectedIndex(0);
        tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GerenciamentoProd dialog = new GerenciamentoProd(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jCUn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPMARCA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTDesc;
    private javax.swing.JTextField jTForn;
    private javax.swing.JTextField jTMarca;
    private javax.swing.JTextField jTPesq;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jVUn;
    // End of variables declaration//GEN-END:variables


     private void mostraPesquisa() {
         tabela = (DefaultTableModel)jTable1.getModel();
         tabela.setNumRows(0);
    Session sesion = HibernateUtil.getSessionFactory().openSession();
    Transaction tx = null;
    try {
        tx = sesion.beginTransaction();
        java.util.List today = sesion.createQuery("From Produtos").list();
     for (Iterator iterator = today.iterator(); iterator.hasNext();){
        Produtos Sal = (Produtos) iterator.next(); 
        tmResultSet.addRow(new Object[]{
            //`enter code here`columns
            Sal.getIdProduto(),
            Sal.getDescricao(),
            Sal.getIdFornecedor(),
            Sal.getIdMarca(),
            Sal.getUnidadeCompra(),
            Sal.getUnidadeVenda(),
        });
        }
        tx.commit();
    } catch (HibernateException e) {
        if (tx != null) {
            tx.rollback();
        }
        e.printStackTrace();
    } finally {
       sesion.close();
    }
        
 
      }
     
     
      private void jTTabelaLinhaSelecionada(JTable tabela) {
           if (jTable1.getSelectedRow()!= -1) {     
          String cod = (jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString();
                   this.id = Integer.parseInt(cod);
                   this.descricao = (jTable1.getValueAt(jTable1.getSelectedRow(),1)).toString();
          this.unCompra = (jTable1.getValueAt(jTable1.getSelectedRow(),4)).toString();
          this.unVenda = (jTable1.getValueAt(jTable1.getSelectedRow(),5)).toString();
                    String idF = (jTable1.getValueAt(jTable1.getSelectedRow(),2)).toString();
                    String idM = (jTable1.getValueAt(jTable1.getSelectedRow(),3)).toString();
          this.fornecedor = Integer.parseInt(idF);
          this.marca = Integer.parseInt(idM);       
                   
          jTDesc.setText(this.descricao);
          jTForn.setText(idF);
          jTMarca.setText(idM);
                   
           }
      /*  if (jTable1.getSelectedRow()!= -1) {
           
          this.id = resultado.get(tabela.getSelectedRow()).getIdProduto();
          this.descricao = resultado.get(tabela.getSelectedRow()).getDescricao();
          this.unCompra = resultado.get(tabela.getSelectedRow()).getUnidadeCompra();
          this.unVenda = resultado.get(tabela.getSelectedRow()).getUnidadeVenda();
          this.fornecedor = resultado.get(tabela.getSelectedRow()).getIdFornecedor();
          this.marca = resultado.get(tabela.getSelectedRow()).getIdMarca();
          
          
          System.out.println("Conheça nossos produtos: "+this.descricao);
          
          
        }*/
        
        
     }  
      
   
      

    private void pesquisaSelecionada(String text) {
        tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Criteria crit = sesion.createCriteria(Produtos.class);
        crit.add(Restrictions.like("descricao",text+"%"));
        java.util.List results = crit.list();
        for (Iterator iterator = results.iterator(); iterator.hasNext();){
        Produtos Sal = (Produtos) iterator.next(); 
        tmResultSet.addRow(new Object[]{
            //`enter code here`columns
            Sal.getIdProduto(),
            Sal.getDescricao(),
            Sal.getIdFornecedor(),
            Sal.getIdMarca(),
            Sal.getUnidadeCompra(),
            Sal.getUnidadeVenda(),
        });
         
        }
        
            /*     
    Session sesion = HibernateUtil.getSessionFactory().openSession();
    Transaction tx = null;
    try {
        tx = sesion.beginTransaction();
        java.util.List today = sesion.createQuery("From Produtos").list();
     for (Iterator iterator = today.iterator(); iterator.hasNext();){
        Produtos Sal = (Produtos) iterator.next(); 
       
        }
        tx.commit();
    } catch (HibernateException e) {
        if (tx != null) {
            tx.rollback();
        }
        e.printStackTrace();
    } finally {
       sesion.close();
    }
*/
    }

     private void mostraPesquisaFiltro(String text) {
        tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Criteria crit = sesion.createCriteria(Fornecedores.class);
        crit.add(Restrictions.like("nomeForn",text+"%"));
        java.util.List results = crit.list();
        for (Iterator iterator = results.iterator(); iterator.hasNext();){
        Fornecedores Sal = (Fornecedores) iterator.next(); 
        
 
        JMenuItem item = new JMenuItem(Sal.getNomeForn()+","+Sal.getIdForn());
          item.addActionListener(new ActionListener() {
             
            @Override
            public void actionPerformed(ActionEvent arg0)
            {
                String mods = item.getText();
                 String campos[] = mods.split(",");
                jTForn.setText(campos[1]);
              
               // id_Forn = Integer.parseInt(campos[1]);
             }
          });
        
        
        jPopupF.add(item);
        
        }    }
 private void mostraPesquisaFiltroMarca(String text) {
        tabela = (DefaultTableModel)jTable1.getModel();
        tabela.setNumRows(0);
        Session sesion = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = null;
        Criteria crit = sesion.createCriteria(Marca.class);
        crit.add(Restrictions.like("nomeMarca",text+"%"));
        java.util.List results = crit.list();
        for (Iterator iterator = results.iterator(); iterator.hasNext();){
        Marca Sal = (Marca) iterator.next(); 
        
 
        JMenuItem item = new JMenuItem(Sal.getNomeMarca()+","+Sal.getIdMarca());
          item.addActionListener(new ActionListener() {
             
            @Override
            public void actionPerformed(ActionEvent arg0)
            {
                String mods = item.getText();
                 String campos[] = mods.split(",");
                jTMarca.setText(campos[1]);
              
               // id_Forn = Integer.parseInt(campos[1]);
             }
          });
        
        
        jPMARCA.add(item);
        
        }    }


}
